made length of descriptions and number of timings configurable in bac…
Kanti/server-timing pull request #41
Opened 2024-02-07 10:37 UTC by CamillH

…kend

2024-02-07 13:52 UTC, Kanti requested changes

2024-02-07 13:52 UTC, Kanti commented on ext_conf_template.txt
> +number_of_timings = 70
maybe set this to 30?

2024-02-07 13:52 UTC, Kanti commented on ext_conf_template.txt
> +length_of_description = 100
maybe set this to 60

2024-02-07 13:52 UTC, Kanti commented on Classes/Utility/TimingUtility.php
> +            if ($duration >= ($durations[$this->configService->getMaxNumberOfTimings() - 1] ?? 0)) {
`($durations[$this->configService->getMaxNumberOfTimings() - 1] ?? 0)` should be a variable outside the loop

2024-02-07 13:58 UTC, CamillH commented on ext_conf_template.txt
> +number_of_timings = 70
reasonable

2024-02-09 10:58 UTC, Kanti approved these changes

2024-02-09 10:58 UTC, merged